apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: orders
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: orders
  strategy:
    canary:
      stableService: orders-stable
      canaryService: orders-canary
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: error-rate-check
            args:
              - name: service
                value: orders-canary
        - setWeight: 60
        - analysis:
            templates:
              - templateName: error-rate-check
            args:
              - name: service
                value: orders-canary
        - setWeight: 100
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: ghcr.io/wilsonm1/gitops-canary-demo:be091ef3317b0745d7af9ba36994c19138ae99d5
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: v1
            - name: FAIL_RATE
              value: "0"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: orders-stable
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: orders-canary
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 8080
